# Configuração do Supabase para produção
project_id = "pxpscjyeqmqqxzbttbep"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://mrxbr.app"
additional_redirect_urls = ["https://mrxbr.app", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true

[auth.sms]
enable_signup = false

[analytics]
enabled = false
