# Arquivo de configuração do Supabase
project_id = "pxpscjyeqmqqxzbttbep"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://mrxbr.app"
additional_redirect_urls = ["https://mrxbr.app", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true

[auth.sms]
enable_signup = false

[auth.password]
hibp_enabled = true
hibp_api_key = { env = "HIBP_API_KEY" }
min_length = 12
min_uppercase = 1
min_lowercase = 1
min_number = 1
min_special = 1

[auth.otp]
expiry_duration = "300s"  # 5 minutos conforme política interna

[analytics]
enabled = false
# Deploy trigger para aplicar correções frontend - dom 31 ago 2025 22:22:31 -03
