-- Inserir Marya Aliny como nova colaboradora
INSERT INTO colaboradores (
    nome, 
    email, 
    cargo, 
    departamento, 
    empresa_id, 
    status, 
    tipo_contrato,
    data_admissao,
    data_nascimento,
    sexo,
    salario_base,
    telefone,
    celular,
    endereco,
    cep,
    cidade,
    estado,
    estado_civil,
    escolaridade,
    nome_mae,
    nome_pai,
    contato_emergencia_nome,
    contato_emergencia_telefone,
    contato_emergencia_parentesco,
    cpf,
    rg,
    rg_orgao_emissor,
    ctps,
    ctps_serie,
    pis_pasep,
    titulo_eleitor,
    reservista,
    vale_transporte,
    vale_refeicao,
    valor_vale_transporte,
    valor_vale_refeicao,
    plano_saude,
    plano_odontologico,
    tem_filhos_menores_14,
    quantidade_filhos,
    filhos,
    banco,
    agencia,
    conta,
    tipo_conta,
    pix,
    created_by
) VALUES (
    'Marya Aliny Santos de Melo',
    'maryaalinymelo@gmail.com',
    'DIR FINANCEIRA',
    'FINANCEIRO',
    'be32bc04-a953-46b8-bd8a-dc9c8bf87b51',
    'ATIVO',
    'CLT',
    '2025-08-19',
    '1995-05-15',
    'FEMININO',
    8000.00,
    '(63) 99945-1408',
    '',
    'Qd. 204 Sul, Alameda 10, Lt. 2-A',
    '77020-468',
    'Palmas',
    'TO',
    'SOLTEIRO',
    'SUPERIOR',
    'Maria Santos de Melo',
    'José Aliny Santos',
    '',
    '',
    '',
    '042.349.261-67',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    false,
    false,
    0.00,
    0.00,
    false,
    false,
    false,
    0,
    '[]'::jsonb,
    'BANCO DO BRASIL',
    '2997-1',
    '12345-6',
    'CORRENTE',
    '042.349.261-67',
    (SELECT user_id FROM profiles WHERE role = 'superuser' AND is_active = true LIMIT 1)
);

-- Criar um histórico para este novo cadastro
INSERT INTO empresa_historico (
    empresa_id,
    tipo,
    titulo,
    descricao,
    usuario_nome,
    created_by,
    meta
) VALUES (
    'be32bc04-a953-46b8-bd8a-dc9c8bf87b51',
    'colaborador',
    'Colaborador recadastrado',
    'Colaborador "Marya Aliny Santos de Melo" foi recadastrado como DIR FINANCEIRA (dados anteriores foram sobrescritos por erro)',
    'Sistema',
    (SELECT user_id FROM profiles WHERE role = 'superuser' AND is_active = true LIMIT 1),
    jsonb_build_object('cargo', 'DIR FINANCEIRA', 'departamento', 'FINANCEIRO', 'motivo', 'dados_sobrescritos')
);