// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxpscjyeqmqqxzbttbep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4cHNjanllcW1xcXh6YnR0YmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzMzMzksImV4cCI6MjA3MDI0OTMzOX0.pXHV4HvzqVpiLLoJIgtZ6hL9kxuJIPzIZXNHMfu4Wzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});